baseURL = "https://moon-php.com/"
languageCode = "en-us"
title = "Moon PHP"
theme = "kube"
[params]
    github = "https://github.com/moon-php/"
	twitter = "https://twitter.com/damiano_dev"
	description = "Moon PHP micro-framework based on interchangeable PSR-only components"
[[menu.main]]
    name = "Docs"
    weight = 1
    url = "/docs/"
[[menu.main]]
    name = "Tutorial"
    weight = 2
	url = "/tutorial/"
[[menu.main]]
    name = "Github"
    weight = 3
	url = "https://github.com/moon-php/"